name: Deploy to Docker
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE }}:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: save key to file
      run: echo "${{ secrets.VM_KEY }}" > key
    - name: set permissions on file
      run: chmod 400 key
    - name: Restart container
      run: ssh -i key -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} 'sudo docker stop $CONTAINER_NAME && sudo docker rm $CONTAINER_NAME && sudo docker pull $CONTAINER_IMAGE:latest && sudo docker run $CONTAINER_PARAMETERS --name $CONTAINER_NAME --restart unless-stopped -d $CONTAINER_IMAGE'
    
