name: Deploy to VM
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: zulu
    - name: Package
      run: mvn -B package --file pom.xml
    - name: Save key to file
      run: echo "${{ secrets.VM_KEY }}" > key
    - name: Set permissions on file
      run: chmod 400 key
    - name: SCP files to server
      run: scp -i key -o StrictHostKeyChecking=no target/app.jar ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USERNAME }}/server
    - name: Restart app
      run: ssh -i key -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "sudo systemctl restart todo-app.service"
