name: Deploy to VM
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: zulu
    - name: package archive
      run: mvn -B package --file pom.xml -Djar.finalName=todo
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_KEY }}
        source: "target/todo.war"
        target: "/home/azureuser/server"
